# This is a basic workflow to help you get started with Actions
name: CMake LongQt-model

# Controls when the action will run. Manually triggered
on: workflow_dispatch

env:
  CMAKE_INSTALL_PREFIX: ~/install

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
# This workflow contains a single job called "build"
  build: 
# The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }} 
    strategy:
      fail-fast: false
      matrix:
        config:
#          - {
#              name: "Windows Latest MSVC",
#              os: windows-latest,
#              build_type: "Release",
#              cc: "cl",
#              cxx: "cl",
#              environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
#              generators: "Visual Studio 16 2019"
#            }
          - {
              name: "Ubuntu_Latest",
              os: ubuntu-latest,
              build_type: "Release",
              cc: "gcc",
              cxx: "g++",
              generators: "Unix Makefiles"
            }
          - {
              name: "macOS Latest Clang",
              os: macos-latest,
              build_type: "Release",
              cc: "clang",
              cxx: "clang++",
              generators: "Ninja"
            }
    
    steps:
  #      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install cmake
          cmake --version
          cmd "${{ matrix.config.environment_script }}"
 
      - name: Install dependencies on ubuntu
        if: startsWith(matrix.config.name, 'Ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes cmake build-essential qt5-default
          cmake --version
          gcc --version

      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install cmake ninja qt@5
          brew link qt5 --force
          ninja --version
          cmake --version

      - name: Configure
        shell: bash
        run: |
          mkdir -p build
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_INSTALL_PREFIX:PATH=./install \
            -G "${{ matrix.config.generators }}"

      - name: Build
        shell: bash
        run: |
          cmake --build . --config ${{ matrix.config.build_type }}
 
      - name: Install
        shell: bash
        run: cmake --install . --prefix ./install
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LongQt-model-${{ runner.os }}
          path: ./install

